import { User, Report, CommunityReport } from "@/types";

export const mockUser: User = {
  id: "1",
  email: "john.doe@email.com",
  name: "John Doe",
  phone: "+1 (555) 123-4567",
  address: "123 Main St, Anytown, USA",
  avatar: "/placeholder.svg",
  joinedAt: new Date("2023-01-15"),
};

export const mockReports: Report[] = [
  {
    id: "1",
    title: "Pothole on Main Street",
    description: "Large pothole causing traffic issues and potential vehicle damage. Located near the intersection with Oak Avenue.",
    category: "Road Maintenance",
    status: "in-progress",
    priority: "high",
    location: {
      lat: 40.7128,
      lng: -74.0060,
      address: "Main St & Oak Ave, Anytown, USA",
    },
    images: ["/placeholder.svg"],
    userId: "1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-18"),
    upvotes: 12,
  },
  {
    id: "2",
    title: "Broken Streetlight",
    description: "Streetlight has been out for over a week, creating safety concerns for pedestrians.",
    category: "Lighting",
    status: "pending",
    priority: "medium",
    location: {
      lat: 40.7589,
      lng: -73.9851,
      address: "Central Park West, New York, NY",
    },
    images: [],
    userId: "1",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    upvotes: 8,
  },
  {
    id: "3",
    title: "Graffiti on Public Building",
    description: "Vandalism on the side of the community center building. Needs cleaning.",
    category: "Vandalism",
    status: "resolved",
    priority: "low",
    location: {
      lat: 40.7505,
      lng: -73.9934,
      address: "Community Center, Anytown, USA",
    },
    images: ["/placeholder.svg"],
    userId: "1",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-12"),
    upvotes: 5,
  },
];

export const mockCommunityReports: CommunityReport[] = [
  {
    id: "4",
    title: "Fallen Tree Blocking Sidewalk",
    description: "Large tree fell during last night's storm and is completely blocking the sidewalk on Elm Street.",
    category: "Emergency",
    status: "pending",
    priority: "high",
    location: {
      lat: 40.7614,
      lng: -73.9776,
      address: "Elm Street, Anytown, USA",
    },
    images: ["/placeholder.svg"],
    userId: "2",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    upvotes: 25,
    isUpvoted: false,
    author: {
      name: "Sarah Johnson",
      avatar: "/placeholder.svg",
    },
    commentsCount: 8,
  },
  {
    id: "5",
    title: "Park Playground Equipment Damaged",
    description: "The swing set in Riverside Park has broken chains and is unsafe for children to use.",
    category: "Parks & Recreation",
    status: "pending",
    priority: "medium",
    location: {
      lat: 40.7831,
      lng: -73.9712,
      address: "Riverside Park, Anytown, USA",
    },
    images: [],
    userId: "3",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
    upvotes: 15,
    isUpvoted: true,
    author: {
      name: "Mike Chen",
      avatar: "/placeholder.svg",
    },
    commentsCount: 3,
  },
  {
    id: "6",
    title: "Illegal Dumping in Alley",
    description: "Someone has dumped furniture and appliances in the alley behind Oak Street. Needs immediate cleanup.",
    category: "Waste Management",
    status: "in-progress",
    priority: "medium",
    location: {
      lat: 40.7282,
      lng: -74.0776,
      address: "Oak Street Alley, Anytown, USA",
    },
    images: ["/placeholder.svg"],
    userId: "4",
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-19"),
    upvotes: 18,
    isUpvoted: false,
    author: {
      name: "Emily Rodriguez",
      avatar: "/placeholder.svg",
    },
    commentsCount: 12,
  },
];

export const categories = [
  "Road Maintenance",
  "Lighting",
  "Vandalism",
  "Emergency",
  "Parks & Recreation",
  "Waste Management",
  "Water & Utilities",
  "Traffic",
  "Other",
];